bf16: true
cutoff_len: 1024
dataset: identity
dataset_dir: data
ddp_timeout: 180000000
do_train: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
loraplus_lr_ratio: 16
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/Llama-3.2-3B-Instruct/lora/train_llama_3_2_v3
packing: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: llama3
val_size: 0.1
warmup_steps: 0
